version: '3.8'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:22.8
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
volumes:
  clickhouse_data: